### PR TITLE
Reworked all graphics + improvements

### PR DESCRIPTION
**Pull request by snouz**
Hi, I've taken upon myself to do some visual rework of the mod:

Changelog:
- Redone all icons and tech icons, in the correct resolution
- New experimental charging station
- Slightly increased contrast of trains
- improved charging station ground integration
- dedicated refurbishment icons
- Removed some useless images
- New thumbnail

Merry Christmas!

acceleration-batterydestroyed-acceleration-batterydischarged-acceleration-batteryelectric-artillery-wagonelectric-cargo-wagonelectric-locomotiveelectric-locomotive-wagonelectric-train-charging-stationexperimental-electric-train-charging-stationalkaline-batterybatterybattery_lightdestroyed-batterydischarged-batteryfast-batteryrefurbishment-batteryhr_experimental_space_charging_stationtech-efficiency-battery-packtech-electric-artillery-wagontech-electric-locomotive-wagontech-electric-trainstech-electric-trains-braking-force-1tech-electric-trains-experimental-charging
thumbnail
hr_space_charging_station

### CODE REVIEW

**Comment by snouz** [comment]
@nerfkidjcb @Fragjacker

**Comment by nerfkidjcb** [comment]
Damn, this is all I could have wanted for Christmas... I'll start play testing this now and make sure its in alignment

Thank you and merry Christmas too <3

**Comment by nerfkidjcb** [comment]
The thumbnail looks good, but I notice the background image of the original is still there, but cropped as the new image is 256x256, would you either be able to resize to not crop the old background image? :D

**Comment by nerfkidjcb** [comment]
(Sorry I'm not doing this in a GH code review format) Ah.. I see the you have merged the cargo wagon graphics into the wagon locomotive. I kept an intentional difference in the red/green on top of the locomotive to indicate direction of power transfer, would you be able to restore this difference?

**Comment by nerfkidjcb** [comment]
If you could also update the readme to use your graphics that would be ideal.

Otherwise this looks really good, and I appreciate you putting in the effort to change what was defo in need of some attention

**Comment by snouz** [comment]
No problem, I'll apply the changes as soon as I have time, maybe tonight or tomorrow

**Comment by snouz** [comment]
Please tell me if the changes are what you were hoping for

I made the color on top of the wagon loco a separate layer for space saving (files with a lot of transparency are like 15x lighter)

**Comment by nerfkidjcb** [comment]
Great stuff, yeah I'm happy with that. Thank you so much!

You'll see your changes in the next update which I will release in the next couple days.

Happy holidays

**Pull request merged**
