### PR TITLE
Added Russian translation.

### PR DESCRIPTION
**Pull request by umbraphile**
Adds ru- locale to the mod.

### CODE REVIEW

**Comment by nerfkidjcb** [comment]
Hi! Sorry, I hadn't seen this. Would you be able to also create the translation for the extended train setting that I just implemented in 0.3.4? Thanks so much!!

**Comment by nerfkidjcb** [comment]
Actually its all fine

**Comment by nerfkidjcb** [comment]
Will just take it for now to get 0.3.5 out there

**Comment by umbraphile** [comment]
Hello! Translated the extended train setting as you've asked.

**Pull request merged**
